[project]
name = "certs"
version = "0.1.0"
description = "Show certificates on the file system"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiofiles>=24.1.0",
    "cryptography>=44.0.0",
    "pandas>=2.2.3",
    "tabulate>=0.9.0",
    "tqdm>=4.67.1",
]
