#! /usr/bin/env bash

# Compare DNS databases between AWS and DYN
# Usage: ./dns_check domain

if (($# != 1)) || [[ $1 == -* ]]
then
   exit 1
fi

zone="$1"

aws="$(mktemp)"_AWS
dyn="$(mktemp)"_DYN

# aws
# For ref, the sed is needed in case the version of bind-utils used doesn't have this commit: https://source.isc.org/cgi-bin/gitweb.cgi?p=bind9.git;a=commit;h=9a36fb86f5019f25705d25ea729d03fcf8ecaa95
while read -r domain _ _ type ip
do
   echo "$domain" "$type" "$ip"
done < <(cli53 export -f "$zone" | grep -v '\(ORIGIN\|SOA\)') | sed 's/;/\\;/g' | sort > "$aws"

# dyn
while read -r domain _ _ type ip
do
   echo "$domain" "$type" "$ip"
done < <(dig +noall +answer AXFR "$zone" @xfrout1.dynect.net | grep -v '\(ORIGIN\|SOA\)') | sort > "$dyn"

echo "Zone: $zone"

if [[ -t 1 ]] && colordiff -v >/dev/null 2>&1
then
   colordiff -wBU0 "$aws" "$dyn"
else
   diff      -wBU0 "$aws" "$dyn"
fi
